name: Trigger Deploy

on:
  push:
    branches: [develop]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.DEPLOY_REPO_PAT }}
          repository: zidsa/deploy-soft-theme-vitrin
          event-type: source-updated
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref_name }}"}'